version: '3.9'
services:
  app:
    build: ./
#    command: [ "go", "run", "main.go" ]
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=assignment3go
    ports:
      - "5436:5432"
volumes:
  db: